topicSharingProject/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name="login"),
    path("logout/",auth_views.LogoutView.as_view(), name="logout"),
    path("signup/",views.SignUp.as_view(),name="signup"),
]

topicSharingProject/groups/urls.py
from django.urls import path
from . import views

app_name = "groups"

urlpatterns = [
    path('/', views.ListGroups.as_view(),name = "all"),
    path('new/', views.CreateGroup.as_view(),name = "create"),
    path('posts/in/(?P<slug>[-\w]+)/', views.SingleGroup.as_view(),name = "single"),
    path('join/(?P<slug>[-\w]+)/', views.JoinGroup.as_view(),name = "join"),
    path('leave/(?P<slug>[-\w]+)/', views.LeaveGroup.as_view(),name = "leave"),
]

topicSharingProject/topicSharingProject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

topicSharingProject/accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

topicSharingProject/groups/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.text import slugify

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()


from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    slug = models.SlugField(all_unicode = True, unique=True)
    description = models.TextField(blank = True, default='')
    description_html = models.TextField(editable=Fasle,default='')
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name


    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)


    def get_absolute_url(self):
        return reverse("groups:single",kwargs={"slug":self.slug})

    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name = "memberships")
    user = models.ForeignKey(User,related_name="user_groups")

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

topicSharingProject/posts/models.py
from django.db import models

# Create your models here.

topicSharingProject/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

topicSharingProject/accounts/views.py
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView

from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/sign.html"

topicSharingProject/groups/views.py
from django.contrib import messages
from django.contrib.suth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group,GroupMember
from . import models

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DeleteView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args, **kwargs):
        return reverse("groups:single",kwargs ={"slug":self.kwargs.get("slug")})


    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug = self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user = self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("You are already a member of {}.".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group!".format(group.name))

        return super().get(request, *args, **kwargs)



class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self.*args, **kwargs):
        return reverse("groups:single", kwargs = {"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:
            membership = models.GroupMember.objects.filter(
            user = self.request.user,
            group__slug = self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
            self.request,
            "Can't leave since you are not in it"
            )
        else:
            membership.detele()
            message.success(
            self.request,
            "You have now successfully left this group."
            )

        return super().get(request, *args, **kwargs)

        

topicSharingProject/posts/views.py
from django.shortcuts import render

# Create your views here.

topicSharingProject/accounts/templates/login.html
{% extends "base.html"%}

{% block content %}

<div>
  <h3>Login</h3>
  <form method="POST">
    {% csrf_token %}
  <<input type="submit" value="Login">
  </form>
</div>

{% endblock %}

topicSharingProject/accounts/templates/signup.html
{% extends "base.html" %}

{% block content %}

<div>
  <h2>Please register your account</h2>
  <form method="POST">
    { % csrf_token % }
    <input type="submit" value="Register">
  </form>
</div>
{% endblock %}

topicSharingProject/groups/templates/group/group_base.html
{% extends "base.html" %}
{% block content %}

<div>
  <div >
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

topicSharingProject/groups/templates/group/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}


<h1>{{group.name}}</h1>
<h2> Member Count: {{group.members.count}}</h2>

  <div>


				{% if user in group.members.all %}
					<a href="{% url 'groups:leave' slug=group.slug %}" ><span >Leave</span></a>
				{% else %}
					<a href="{% url 'groups:join' slug=group.slug %}"><span>Join</span></a>
				{% endif %}
</div>

{% endblock %}


{% block group_content %}

<div>
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}

topicSharingProject/groups/templates/group/group_form.html
{% extends "groups/group_base.html" %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}">
  	{% csrf_token %}
  	<input type="submit" value="Create">
  </form>
{% endblock %}

topicSharingProject/groups/templates/group/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div>
	<div>
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" ><span >Create New Group!</span> </a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div>
	<div>
		{% for group in object_list %}
		  <a href="{% url 'groups:single' slug=group.slug %}">
			     <h3>{{ group.name }}</h3>
			<div>
				{{ group.description_html|safe }}
				<div >
					<div>
						<span>{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div>
						<span >{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

topicSharingProject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sharing is caring</title>
    <link rel="stylesheet" href="{% static 'css/stylesheet.css'%}">
  </head>
  <body>

  </body>

  <script src="{% static "javascript/index.js"% }" type="text/javascript" ></script>
</html>